--    CREATE TABLE IF NOT EXISTS public.newtable (
--      id serial PRIMARY KEY,
--       name VARCHAR(255),
--       timers integer
--    );


    CREATE TABLE IF NOT EXISTS t_role (
      id BIGINT NOT NULL,
       name VARCHAR(255),
       CONSTRAINT pk_t_role PRIMARY KEY (id)
    );
    CREATE TABLE IF NOT EXISTS t_user (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       username VARCHAR(255),
       password VARCHAR(255),
       CONSTRAINT pk_t_user PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS t_user_roles (
      user_id BIGINT NOT NULL,
       roles_id BIGINT NOT NULL,
       CONSTRAINT pk_t_user_roles PRIMARY KEY (user_id, roles_id)
    );
